version: 2.1

# orbs:
#   python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      # - python/load-cache
      # - python/save-cache
      - run:
          command: docker build . --tag augmentation_generator
          name: Build
      - run:
          command: docker run augmentation_generator
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
